server:
  port: 9200
  address: 0.0.0.0
spring:
  application:
    name: item-service
  datasource:
    url: jdbc:postgresql://localhost:5432/restik
    username: restik-items
    password: pass1234

  kafka:
    consumer:
      auto-offset-reset: earliest
      group-id: item-service
      value-deserializer: org.springframework.kafka.support.serializer.JsonSerializer
    producer:
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

  redis:
    host: localhost
    port: 6379
    password: pass1234
    jedis:
      pool:
        max-active: 7
        max-idle: 7
        min-idle: 2
        max-wait: -1ms

  cache:
    redis:
      cache-null-values: false
      time-to-live: 600000
      use-key-prefix: true
    type: redis

item-service:
  topic: test-topic